use_frameworks!

target 'SMNetworkManager_Example' do
  pod 'SMNetworkManager', :path => '../'

  target 'SMNetworkManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
