use_frameworks!

target 'SMNetworkingManager_Example' do
  pod 'SMNetworkingManager', :path => '../'

  target 'SMNetworkingManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
